# Generated by Django 2.2.1 on 2019-05-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('photo', models.CharField(blank=True, max_length=999)),
                ('date_of_signup', models.DateTimeField()),
            ],
        ),
    ]
