# Generated by Django 2.2.1 on 2019-05-13 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameModel(
            old_name='EstatesCategory',
            new_name='EstateCategory',
        ),
        migrations.RenameModel(
            old_name='EstatesImage',
            new_name='EstateImage',
        ),
        migrations.RemoveField(
            model_name='estates',
            name='notendur',
        ),
        migrations.AddField(
            model_name='estates',
            name='short_description',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='estates',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estates',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='StarRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estates.Estates')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.IntegerField()),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estates.Kingdom')),
            ],
        ),
        migrations.CreateModel(
            name='EstateDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('towers', models.IntegerField()),
                ('ballroom', models.BooleanField()),
                ('tower_office', models.BooleanField()),
                ('moat', models.BooleanField()),
                ('stables', models.BooleanField()),
                ('dungeon', models.BooleanField()),
                ('drawbridge', models.BooleanField()),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estates.Estates')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=255)),
                ('region_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estates.RegionCode')),
            ],
        ),
        migrations.AddField(
            model_name='estates',
            name='address',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='estates.Address'),
            preserve_default=False,
        ),
    ]
