# Generated by Django 2.2.1 on 2019-05-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0004_starrating_has_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatedetails',
            name='ballroom',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='estatedetails',
            name='drawbridge',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='estatedetails',
            name='dungeon',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='estatedetails',
            name='moat',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='estatedetails',
            name='stables',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='estatedetails',
            name='tower_office',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='estates',
            name='on_sale',
            field=models.BooleanField(blank=True),
        ),
    ]
