# Generated by Django 2.2.1 on 2019-05-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0005_auto_20190515_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatedetails',
            name='estate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estates.Estates'),
        ),
    ]
