# Generated by Django 2.2.1 on 2019-05-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0006_auto_20190516_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='estates',
            name='ballroom',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='estates',
            name='drawbridge',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='estates',
            name='dungeon',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='estates',
            name='floors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estates',
            name='moat',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='estates',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estates',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estates',
            name='stables',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='estates',
            name='tower_office',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='estates',
            name='towers',
            field=models.IntegerField(default=0),
        ),
    ]
