# Generated by Django 2.2.1 on 2019-05-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0007_auto_20190516_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estates',
            name='on_sale',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
