# Generated by Django 2.2.1 on 2019-05-15 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0004_starrating_has_star'),
        ('user', '0002_auto_20190513_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='credit_amount',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='sec_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estates.Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='owned_property',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='estates.Estates'),
            preserve_default=False,
        ),
    ]
