# Generated by Django 2.2.1 on 2019-05-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190515_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='owned_property',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
