# Generated by Django 2.2.1 on 2019-05-16 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0006_auto_20190516_1339'),
        ('user', '0004_auto_20190516_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estates.RegionCode'),
        ),
    ]
