# Generated by Django 2.2.1 on 2019-05-16 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0006_auto_20190516_1339'),
        ('user', '0006_userprofile_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kingdom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estates.Kingdom'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ssn',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
